name: Daily News AI Bot

on:
  schedule:
    - cron: '30 1 * * *' 
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install Libraries
        run: |
          pip install requests beautifulsoup4 lxml

      - name: 4. Run Scraper (Get News)
        run: python scraper.py

      - name: 5. Run Cleaner (Filter Data)
        run: python cut.py

      - name: 6. Run AI Magic (Summarize)
        
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python ai_magic.py

      - name: 7. Run Final Cleaner (Cut3)
        run: python cut3.py

      - name: 8. Commit and Push
        run: |
          git config --global user.name "NewsBot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "ðŸ¤– News Updated & Cleaned" || exit 0
          git push
